name: xiaoshoubiao
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.1'
          channel: "stable"
      - name: "Web Build 🔧"
        run: |
          flutter pub get
          flutter build web
      - name: "Web Deploy 🚀"
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: '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'
          branch: gh-pages
          folder: build/web

