name: xiaoshoubiao
on:
  push:
    branches:
      - master
jobs:
 build:
    name: Build Web
    env:
      my_secret: ${{secrets.GITHUB1_TOKEN}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.1'
          channel: "stable"
      - name: "Web Build 🔧"
        run: |
          flutter pub get
          flutter build web --web-renderer html --release --base-href="/superpacecalcweb/"
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB1_TOKEN }}
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build/web

          
