name: xiaoshoubiao
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.1'
          channel: "stable"
      - name: "Web Build 🔧"
        run: |
          flutter pub get
          flutter build web --release
      - name: "Web Deploy 🚀"
        # https://github.com/JamesIves/github-pages-deploy-action
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: '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'
          branch: gh-pages
          folder: build/web

