name: xiaoshoubiao
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build Web
    env:
      my_secret: ${{secrets.commit_secret}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
      - run: flutter build web
      - name: "Web Deploy🚀"
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: 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
          BASE_BRANCH: master
          BRANCH: gh-pages
          FOLDER: build/web


